name: Deploy to Firebase Hosting on PR

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Validate required secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UVBUNNY_APP }}
        run: |
          echo "🔍 Validating required GitHub Secrets for PR preview..."
          # Secret validation logic...
          echo "✅ All required secrets are configured"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Create environment files from secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          mkdir -p src/environments
          echo "// Auto-generated environment.ts" > src/environments/environment.ts
          echo "export const environment = { production: false, firebase: {" >> src/environments/environment.ts
          echo "  apiKey: '${FIREBASE_API_KEY}'," >> src/environments/environment.ts
          echo "  authDomain: '${FIREBASE_AUTH_DOMAIN}'," >> src/environments/environment.ts
          echo "  projectId: '${FIREBASE_PROJECT_ID}'," >> src/environments/environment.ts
          echo "  storageBucket: '${FIREBASE_STORAGE_BUCKET}'," >> src/environments/environment.ts
          echo "  messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}'," >> src/environments/environment.ts
          echo "  appId: '${FIREBASE_APP_ID}'," >> src/environments/environment.ts
          echo "  measurementId: '${FIREBASE_MEASUREMENT_ID}'" >> src/environments/environment.ts
          echo "}};" >> src/environments/environment.ts

          cp src/environments/environment.ts src/environments/environment.prod.ts

      - name: Debug environment.ts existence
        run: |
          echo "🔍 Checking if environment.ts and environment.prod.ts exist..."
          ls -l src/environments/
          cat src/environments/environment.ts || echo "❌ environment.ts not found"
          cat src/environments/environment.prod.ts || echo "❌ environment.prod.ts not found"

      - name: Build application for preview
        run: |
          echo "🏗️ Building application for PR preview..."
          npm run build

      - name: Deploy to Firebase Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UVBUNNY_APP }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: preview
          expires: 7d

      - name: Cleanup environment files
        if: always()
        run: |
          echo "🧹 Cleaning up generated environment files..."
          rm -f src/environments/environment.ts
          rm -f src/environments/environment.prod.ts
          echo "✅ Cleanup completed"
