name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [main]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Create environment files
        run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  firebase: {" >> src/environments/environment.prod.ts
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/environments/environment.prod.ts
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> src/environments/environment.prod.ts
          echo "    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> src/environments/environment.prod.ts
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> src/environments/environment.prod.ts
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> src/environments/environment.prod.ts
          echo "    appId: '${{ secrets.FIREBASE_APP_ID }}'" >> src/environments/environment.prod.ts
          echo "  }" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts
      - name: Debug generated file
        run: cat src/environments/environment.prod.ts
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UVBUNNY_APP_2025 }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
